// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One audio stream from `ffprobe`.
 */
export type AudioStreamInfo = { codec: string, channels: number, sample_rate: number, bit_rate: number | null, language: string | null, };
