// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Custom encode parameters — used only when a job's preset id is `"custom"`.
 */
export type CustomEncode = { 
/**
 * Output container: `"mp4"` | `"mkv"` | `"avi"`.
 */
container: string, 
/**
 * Video codec: `"h264"` | `"hevc"` | `"av1"` | `"ffv1"` | `"copy"`.
 */
video_codec: string, 
/**
 * Constant-quality value (codec-dependent; ignored for `copy`/`ffv1`).
 */
crf: number | null, 
/**
 * Audio codec: `"aac"` | `"opus"` | `"flac"` | `"copy"`.
 */
audio_codec: string, 
/**
 * Audio bitrate in kbit/s (ignored for `copy`/`flac`).
 */
audio_bitrate_k: number | null, };
