// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subdirectory in the in-app folder browser (ADR-PROJ-001). Read-only listing: a name to show and
 * the absolute path to navigate into or choose. Files are never listed — the browser picks a *folder*.
 */
export type DirEntry = { 
/**
 * Display name (the final path component).
 */
name: string, 
/**
 * Absolute path.
 */
path: string, };
