// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FfmpegTool } from "./FfmpegTool";

/**
 * Availability of the ffmpeg suite. `ready` is true only when **both** `ffmpeg` and `ffprobe` are
 * present — every media feature checks this first and offers the installer when it is false
 * (ADR-PROJ-001, ADR-CORE-037).
 */
export type FfmpegStatus = { 
/**
 * The resolved `ffmpeg` binary, or `None` if it could not be found.
 */
ffmpeg: FfmpegTool | null, 
/**
 * The resolved `ffprobe` binary, or `None` if it could not be found.
 */
ffprobe: FfmpegTool | null, 
/**
 * True when both tools are present and usable.
 */
ready: boolean, };
