// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resolved ffmpeg-suite tool (`ffmpeg` or `ffprobe`) — where it was found and its version.
 */
export type FfmpegTool = { 
/**
 * Absolute path to the resolved binary.
 */
path: string, 
/**
 * Version line reported by the tool (e.g. `"ffmpeg version 6.1.1"`), or `"unknown"`.
 */
version: string, 
/**
 * How it was resolved: `"override"`, `"managed"`, `"path"` or `"system"`.
 */
source: string, };
