// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootKind } from "./RootKind";

/**
 * A starting point in the folder browser's tree: a standard user directory or a drive/volume
 * (ADR-PROJ-001). `label` is what to show, `path` where it points, `kind` which icon to use.
 */
export type FsRoot = { label: string, path: string, kind: RootKind, };
