// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of the in-app ffmpeg install, emitted as `install://progress` (ADR-PROJ-001 §2). The one
 * deliberate network egress — user-initiated, pinned source, SHA-256 verified.
 */
export type InstallProgress = { 
/**
 * `"download"` | `"verify"` | `"extract"` | `"install"` | `"done"` | `"error"`.
 */
phase: string, 
/**
 * 0..100 overall progress; `-1` when the current phase is indeterminate.
 */
percent: number, 
/**
 * A short, localizable-key-free human note (e.g. the failure reason on `"error"`).
 */
message: string | null, };
