// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How thorough an integrity check was (ADR-PROJ-001). `Quick` copies packets to a null muxer — it
 * catches container/header/packet damage in seconds; `Deep` fully decodes every frame — it also catches
 * corruption inside the stream, but takes roughly as long as the video is.
 */
export type IntegrityLevel = "Quick" | "Deep";
