// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrityLevel } from "./IntegrityLevel";

/**
 * The result of checking one video for defects (ADR-PROJ-001). `healthy` is the headline; `sample_errors`
 * carries the first few ffmpeg error lines so the UI can show *why* a file is flagged and offer repair.
 */
export type IntegrityReport = { path: string, 
/**
 * Which check produced this result.
 */
level: IntegrityLevel, 
/**
 * True when ffmpeg reported no errors and exited cleanly.
 */
healthy: boolean, 
/**
 * Number of error lines observed (capped — see `sample_errors`).
 */
error_count: number, 
/**
 * The first handful of ffmpeg `error`-level lines, for display. Truncated when there are many.
 */
sample_errors: Array<string>, };
