// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobState } from "./JobState";

/**
 * A conversion/repair job, as shown in the queue and the status-bar process list.
 */
export type JobDto = { id: string, input_path: string, input_name: string, output_path: string, preset_id: string, state: JobState, 
/**
 * Progress 0..100. Meaningful while `Running`; `Done` is 100.
 */
percent: number, 
/**
 * Failure detail when `state == Failed`.
 */
error: string | null, };
