// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioStreamInfo } from "./AudioStreamInfo";
import type { QualityTier } from "./QualityTier";
import type { SubtitleStreamInfo } from "./SubtitleStreamInfo";
import type { VideoStreamInfo } from "./VideoStreamInfo";

/**
 * Full technical metadata for one video, parsed from `ffprobe -show_format -show_streams` (ADR-PROJ-001).
 */
export type MediaInfo = { path: string, 
/**
 * Container/format long name (e.g. `"QuickTime / MOV"`), from `format.format_long_name`.
 */
container: string, duration_secs: number | null, size_bytes: number, 
/**
 * Overall bit rate in bits/sec.
 */
bit_rate: number | null, 
/**
 * The first video stream, if any.
 */
video: VideoStreamInfo | null, audio: Array<AudioStreamInfo>, subtitles: Array<SubtitleStreamInfo>, 
/**
 * Resolution-based quality tier (derived from the video height).
 */
quality: QualityTier, };
