// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A prepared, webview-playable source for the internal player (ADR-PROJ-001 §5). The frontend passes
 * `file_path` to `convertFileSrc` and plays it in a `<video>`; range/seek is handled by the asset
 * protocol.
 */
export type PreparedPlayback = { 
/**
 * Absolute path (under the app cache) to an MP4 the webview can play.
 */
file_path: string, 
/**
 * True if the source had to be transcoded (not just remuxed) to become playable.
 */
transcoded: boolean, };
