// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A prepared, webview-playable source for the internal player (ADR-PROJ-001 §5). The frontend passes
 * `file_path` to `convertFileSrc` and plays it in a `<video>`; range/seek is handled by the asset
 * protocol.
 */
export type PreparedPlayback = { 
/**
 * Absolute path the webview can play: the **original** file when `direct`, otherwise a prepared MP4
 * under the app cache.
 */
file_path: string, 
/**
 * True if the source had to be transcoded (not just remuxed) to become playable.
 */
transcoded: boolean, 
/**
 * True when the source is played **as-is** — a web container + codec the webview handles natively,
 * so no ffmpeg ran and `file_path` is the original file (which the command then grants the asset
 * scope). No copy, no wait (ADR-PROJ-001 §5).
 */
direct: boolean, };
