// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A conversion/repair preset the user can pick. The ffmpeg argv is built server-side
 * (`jobs::preset`); the frontend maps `id` to a localized name/description.
 */
export type PresetDto = { 
/**
 * `"universal"` | `"efficient"` | `"archive"` | `"repair"` | `"custom"`.
 */
id: string, 
/**
 * Target container extension (e.g. `"mp4"`, `"mkv"`). For `repair` this is the source's container.
 */
container: string, 
/**
 * Whether the output re-encodes the video (false = remux/copy, as in `repair`).
 */
reencodes: boolean, };
