// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resolution-based quality tier (ADR-PROJ-001 §3). Green at >=1080p, ramping to red below. The frontend
 * maps each tier to a HUD colour token and a localized label.
 */
export type QualityTier = "Excellent" | "Good" | "Fair" | "Low" | "Poor";
