// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a browser root, so the frontend can pick an icon without parsing the label
 * (ADR-CORE-005: the meaning is decided here, once).
 */
export type RootKind = "Home" | "Desktop" | "Downloads" | "Documents" | "Videos" | "Drive";
