// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A video file found by scanning a folder — the lightweight card entry, before it is probed.
 */
export type ScannedFile = { 
/**
 * Absolute path to the file.
 */
path: string, 
/**
 * File name with extension (display label).
 */
name: string, 
/**
 * Lower-case extension without the dot (e.g. `"mp4"`).
 */
extension: string, 
/**
 * Size in bytes. `f64` (not `u64`) so the TS side gets a plain number, not a `bigint`; video files
 * are far below the 2^53 exact-integer ceiling.
 */
size_bytes: number, };
