// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subtitle stream from `ffprobe`.
 */
export type SubtitleStreamInfo = { codec: string, language: string | null, };
