// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One video stream from `ffprobe`.
 */
export type VideoStreamInfo = { codec: string, width: number, height: number, 
/**
 * Frames per second (may be fractional, e.g. 29.97).
 */
fps: number, pix_fmt: string | null, bit_rate: number | null, 
/**
 * True when the colour metadata indicates HDR (BT.2020 / PQ / HLG).
 */
hdr: boolean, };
