// Typed wrappers around the Tauri command surface. Types come from the ts-rs bindings (SSOT,
// ADR-CORE-005). Run `npm run gen:types` after touching Rust DTOs.
import { invoke } from "@tauri-apps/api/core";
import type { BuildInfo } from "../bindings/BuildInfo";
import type { CrashReport } from "../bindings/CrashReport";
import type { CustomEncode } from "../bindings/CustomEncode";
import type { DirEntry } from "../bindings/DirEntry";
import type { FfmpegStatus } from "../bindings/FfmpegStatus";
import type { FsRoot } from "../bindings/FsRoot";
import type { JobDto } from "../bindings/JobDto";
import type { LogRecord } from "../bindings/LogRecord";
import type { MediaInfo } from "../bindings/MediaInfo";
import type { PreparedPlayback } from "../bindings/PreparedPlayback";
import type { PresetDto } from "../bindings/PresetDto";
import type { ScannedFile } from "../bindings/ScannedFile";
import type { SettingsDto } from "../bindings/SettingsDto";

/**
 * Typed facade over the backend `#[tauri::command]` surface. Every IPC call in the app flows through
 * here (rule:frontend-architecture), so payload shapes live in one place and match the generated
 * bindings.
 */
export const api = {
  /** App SemVer version (IPC smoke test). */
  appVersion: () => invoke<string>("app_version"),
  /** Build identity: version, channel and the commit the binary was built from. */
  buildInfo: () => invoke<BuildInfo>("build_info"),
  /** Snapshot of the recent log ring buffer for the Logs view's initial load. */
  getRecentLogs: () => invoke<LogRecord[]>("get_recent_logs"),
  /** Read the persisted user settings. */
  getSettings: () => invoke<SettingsDto>("get_settings"),
  /**
   * Partial update — omitted fields keep their current value. Toggling `minimizeToTray` installs or
   * removes the system-tray icon immediately (no restart); toggling `language` re-renders the UI in
   * the new language immediately (no restart) via `useT`/`useSettings`.
   */
  updateSettings: (opts: {
    uiScale?: number;
    minimizeToTray?: boolean;
    language?: string;
    ffmpegPath?: string;
    ffprobePath?: string;
    outputDir?: string;
    jobConcurrency?: number;
    recursiveScan?: boolean;
  }) =>
    invoke<SettingsDto>("update_settings", {
      uiScale: opts.uiScale ?? null,
      minimizeToTray: opts.minimizeToTray ?? null,
      language: opts.language ?? null,
      ffmpegPath: opts.ffmpegPath ?? null,
      ffprobePath: opts.ffprobePath ?? null,
      outputDir: opts.outputDir ?? null,
      jobConcurrency: opts.jobConcurrency ?? null,
      recursiveScan: opts.recursiveScan ?? null,
    }),
  /**
   * Resolve the ffmpeg suite (ffmpeg + ffprobe): settings override → managed install → PATH → platform
   * locations (ADR-PROJ-001). `ready` is false when either is missing, so the UI can offer the installer.
   */
  discoverFfmpeg: () => invoke<FfmpegStatus>("discover_ffmpeg"),
  /** Open an http(s) URL in the default browser (routed through the backend so it is logged). */
  openExternal: (url: string) => invoke<void>("open_external", { url }),
  /**
   * Record a fatal error from the UI runtime in the durable, on-device crash report (ADR-APP-032) and
   * return the report's path. The UI is its own entry point — the Rust panic hook cannot see it — so a
   * crash that does not come through here leaves no evidence at all.
   */
  reportCrash: (report: CrashReport) => invoke<string>("report_crash", { report }),
  /** The crash report a previous run left behind, if it crashed. Consumed on read (shown once). */
  pendingCrash: () => invoke<string | null>("pending_crash"),
  /** End the process after a fatal UI error, with the exit code that says so (`EXIT_UI_CRASH`). */
  exitAfterCrash: () => invoke<void>("exit_after_crash"),
  /**
   * Scan a folder for video files (ADR-PROJ-001). `recursive` overrides the persisted
   * `recursiveScan` setting for this one call; omit it to use the user's default.
   */
  scanFolder: (path: string, recursive?: boolean) =>
    invoke<ScannedFile[]>("scan_folder", { path, recursive: recursive ?? null }),
  /**
   * Full technical metadata for one file, read via `ffprobe` (ADR-PROJ-001). `path` must be one
   * `scanFolder` returned — the backend does not accept an arbitrary frontend-supplied path.
   */
  probeMedia: (path: string) => invoke<MediaInfo>("probe_media", { path }),
  /**
   * One representative-frame thumbnail as a `data:image/jpeg;base64,...` URI, generated by `ffmpeg`
   * and cached by the backend on first request (ADR-PROJ-001).
   */
  getThumbnail: (path: string) => invoke<string>("get_thumbnail", { path }),
  /**
   * Prepare a source video for the internal player (ADR-PROJ-001 §5): probes it and returns a cached,
   * webview-playable MP4 — remuxed when the source is already web-friendly (H.264/AAC), transcoded
   * otherwise (can take a while for a large or exotic file). `path` must be one `scanFolder` returned.
   * The frontend turns the returned `file_path` into a playable URL via `convertFileSrc`
   * (`usePreparePlayer`); may reject if ffmpeg is unavailable or preparation fails.
   */
  preparePlayer: (path: string) => invoke<PreparedPlayback>("prepare_player", { path }),
  /**
   * The in-app HUD folder browser's starting points (ADR-PROJ-001): the standard user directories that
   * resolve on this OS plus the mounted drives/volumes. Read-only. Replaces the OS-native picker
   * (ADR-APP-026: no stock surface, not even the file dialog — the browser is a HUD `Dialog`).
   */
  browseRoots: () => invoke<FsRoot[]>("browse_roots"),
  /**
   * The immediate sub**folders** of `path`, for the folder browser's tree/content pane (ADR-PROJ-001).
   * Read-only; never lists files. Rejects with a typed error if the folder can't be opened.
   */
  browseDir: (path: string) => invoke<DirEntry[]>("browse_dir", { path }),
  /** The built-in conversion/repair presets (ADR-PROJ-001 §4). Labels/descriptions are localized
   * frontend-side from `id` (`src/lib/presets.ts`) — the backend carries no display text. */
  listPresets: () => invoke<PresetDto[]>("list_presets"),
  /**
   * Queue a conversion/repair of one file. `custom` is only meaningful for the `"custom"` preset and
   * is otherwise sent as `null`, mirroring `updateSettings`'s partial-update convention. Output is
   * strictly non-destructive (ADR-PROJ-001): the backend writes to a separate output directory and
   * never touches `inputPath`.
   */
  enqueueJob: (inputPath: string, presetId: string, custom?: CustomEncode) =>
    invoke<JobDto>("enqueue_job", { inputPath, presetId, custom: custom ?? null }),
  /** Request cancellation of a queued or running job by id. The job's terminal state (`Cancelled`)
   * arrives via the `job://update` event, not this call's return value. */
  cancelJob: (id: string) => invoke<void>("cancel_job", { id }),
  /** A snapshot of every job (queued, running, finished), in enqueue order — the status-bar process
   * list's initial load; live changes stream in afterwards via `job://update` (`useJobs`). */
  listJobs: () => invoke<JobDto[]>("list_jobs"),
  /**
   * Download and install a managed ffmpeg suite (ADR-PROJ-001 §2) — the one deliberate network egress,
   * user-initiated, pinned source, SHA-256 verified. Progress streams via the `install://progress`
   * event (`useInstallFfmpeg`); the promise resolves with the freshly discovered `FfmpegStatus` on
   * success, or rejects with a human-readable string on failure (e.g. on macOS, where no managed build
   * is offered and the message points at `brew install ffmpeg` instead).
   */
  installFfmpeg: () => invoke<FfmpegStatus>("install_ffmpeg"),
};
